Feature/1264 optimize bulk import
OS2iot/OS2IoT-backend pull request #140
Opened 2022-02-07 16:31 UTC by AramAlsabti

When importing a .csv file with a large number of IoT devices, timeouts are very likely to occur. The main suspect is the chirpstack API which cannot keep up as numerous calls are made to the API just for a single LoRaWAN device.

This PR refactors this flow:
- Devices are now sent in bulks of 50 instead of all at once, in separate requests.
- Devices with similar metadata are grouped together to minimize requests made to chirpstack.
- If the API's database already has the data, then requests will be made to it instead
- To preserve the individual device error messages, the backend will keep track of any errors during the process and map them to the respective devices. That way, we can still process the rest of the devices from the client

Ideally, the backend would process the CSV file. However, that would mean the user doesn't get "live" updates

[Related frontend PR](https://github.com/OS2iot/OS2IoT-frontend/pull/65) 

Fixes #130

2022-02-15 10:22 UTC, GufCab requested changes

2022-02-15 10:22 UTC, GufCab commented on src/services/device-management/iot-device.service.ts
> +            if (deviceModelMatch?.belongsTo.id !== applicationMatch.belongsTo.id) {
Verify that the DeviceModel actually exists here. Currently it throws an error about the organization not matching if an invalid DeviceModel has been chosen.

2022-02-16 16:16 UTC, AramAlsabti commented on src/entities/dto/chirpstack/chirpstack-device-id.dto.ts
> +export type ChirpstackDeviceId = Pick<ChirpstackDeviceContentsDto, "devEUI">;
Not exactly. This is so we can do the same `x.devEUI` [check](https://github.com/OS2iot/OS2IoT-backend/pull/140/files#diff-16110d18e648539857919a3b5b1f8109e4b241d72d178311bc7aa019de51edeaR358) irregardless of whether the list came from a parameter or from chirpstack.

2022-02-16 16:17 UTC, AramAlsabti commented on src/services/device-management/iot-device.service.ts
> +    async createMany(
Good point!

2022-02-16 16:21 UTC, AramAlsabti commented on src/services/device-management/iot-device.service.ts
> +        await this.mapDtoToIoTDevice(
I agree. The issue is that a device can be invalidated in any one of the operations which is why invalid devices are filtered out before the next operation. Any suggestions?

2022-02-16 16:23 UTC, AramAlsabti commented on src/services/device-management/iot-device.service.ts
> +        await this.mapDtoToIoTDevice(
Good point. I added as documentation to the method

2022-02-16 16:49 UTC, GufCab commented on src/entities/dto/chirpstack/chirpstack-device-id.dto.ts
> +export type ChirpstackDeviceId = Pick<ChirpstackDeviceContentsDto, "devEUI">;
Neat

2022-02-17 09:13 UTC, AramAlsabti commented on src/services/device-management/iot-device.service.ts
> +        await this.mapDtoToIoTDevice(
Alternatively, each method could return a list of valid devices. The input of the next method will be that list. Each method would then have to keep track of valid/invalid devices. I'm not sure if that's just as convoluted as the above, so I'll go with adding a comment at each step

2022-02-17 10:19 UTC, GufCab approved these changes

2022-02-17 13:07 UTC, GufCab approved these changes

2022-02-17 13:30 UTC, merged