Feature/iot 1320 fix sig fox connection
OS2iot/OS2IoT-backend pull request #165
Opened 2022-04-26 12:26 UTC by GufCab

2022-05-16 08:01 UTC, AramAlsabti requested changes
Might be a separate issue. After adding a SigFox connection and editing it (/edit-group), it throws this error irregardless of whatever's in the input fields. It seems to me that the organization id is missing in the request

![billede](https://user-images.githubusercontent.com/92869496/168546326-97d79c39-3c62-40df-8dd8-60eb6aaf275a.png)

2022-05-16 08:05 UTC, AramAlsabti commented on src/controllers/admin-controller/sigfox/sigfox-group.controller.ts
> +			return null;
And wouldn't it be more correct to still throw the error and handle it client-side? The check could be as simple as checking if the following is defined:
```ts
response?.error
```

2022-05-16 13:13 UTC, GufCab commented
> 

This was a frontend issue - fixed in latest push.

2022-05-16 13:15 UTC, GufCab commented on src/controllers/admin-controller/sigfox/sigfox-group.controller.ts
> +			return null;
Could be implemented that way - but the way it's used it is specifically not an error, it's just used as a check if it exists

2022-05-17 09:34 UTC, AramAlsabti approved these changes

2022-05-17 09:35 UTC, merged