Feature/IoT_640 - Downlink queue
OS2iot/OS2iot-backend pull request #257
Opened 2024-09-12 10:37 UTC by augusthjerrild

Added migration for addition of downlink in database. Added endpoints for flushing and getting queue, plus getting historical queue (only take the last 25).

2024-09-13 10:45 UTC, fcv-iteratorIt requested changes

2024-09-17 07:41 UTC, augusthjerrild commented on src/services/data-management/chirpstack-mqtt-listener.service.ts
> +          if (topic.endsWith(this.CHIRPSTACK_MQTT_DEVICE_DATA_TXACK_POSTFIX)) {
Jeg er lidt usikker på hvordan (men er egentlig enig..). Nuværende logik har to scenarier, gateway beskeder eller application beskeder. Jeg vil jo gerne beholde den nuværende logik, hvor jeg dog også kan håndtere 2 nye cases under application. Jeg formodede ikke vi var interesseret i return nogle steder, da der er en logger til slut som jeg tænkte vi gerne ville have. Har du input :-)?

2024-09-17 10:43 UTC, fcv-iteratorIt commented on src/services/data-management/chirpstack-mqtt-listener.service.ts
> +          if (topic.endsWith(this.CHIRPSTACK_MQTT_DEVICE_DATA_TXACK_POSTFIX)) {
Nej det er heller ikke vigtigt, det var bare hvis der lige var en smart måde at lave det

2024-09-17 10:46 UTC, fcv-iteratorIt approved these changes

2024-09-17 10:54 UTC, merged